# Dependabot configuration
# Docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # NPM / PNPM (Dependabot understands pnpm-lock.yaml in the npm ecosystem)
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    versioning-strategy: increase-if-necessary

    # Only update direct dependencies (transitive dependencies remain if there's a security advisory)
    allow:
      - dependency-type: direct

    # ====== GROUPING ======
    # 1) Tooling (devDependencies, build/test/format/lint) → merge minor/patch updates
    groups:
      tooling-minor-patch:
        patterns:
          # TypeScript & TS tooling
          - "typescript"
          - "ts-node"
          - "tsx"
          - "tsup"
          - "@types/*"
          # Test stack
          - "vitest"
          - "@vitest/*"
          # Lint/format
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "prettier"
          - "prettier-*"
          - "@biomejs/*"
          # Bundlers/build tools populer
          - "vite"
          - "@vitejs/*"
          - "rollup"
          - "rollup-*"
          - "webpack"
          - "webpack-*"
          - "babel"
          - "@babel/*"
        update-types: ["minor", "patch"]

      # 2) Runtime (everything except tooling) → automatic via wildcard
      runtime-minor-patch:
        patterns:
          - "*"
        update-types: ["minor", "patch"]

    # Avoid creating major PRs for high-churn tools (you can still update them manually if needed)
    ignore:
      - dependency-name: "typescript"
        update-types: [version-update:semver-major]
      - dependency-name: "@biomejs/biome"
        update-types: [version-update:semver-major]
      - dependency-name: "vitest"
        update-types: [version-update:semver-major]
      - dependency-name: "tsup"
        update-types: [version-update:semver-major]
      - dependency-name: "@types/node"
        update-types: [version-update:semver-major]
      - dependency-name: "@vitest/coverage-v8"
        update-types: [version-update:semver-major]

    # Refine Dependabot PR commit message
    commit-message:
      prefix: "chore"
      include: "scope"

  # Update GitHub Actions in .github/workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [ci, dependencies]
